import process from 'node:process'
import react from '@vitejs/plugin-react'
import UnoCSS from 'unocss/vite'
import { defineConfig } from 'vite'

// https://vite.dev/config/
export default defineConfig({
  // generated by ai
  define: {
    __DEV__: process.env.NODE_ENV === 'development',
  },
  plugins: [react(), UnoCSS()],
})
